version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d 
    ports:
      - '5432:5432'

  pgadmin:                     
    image: dpage/pgadmin4
    env_file:
      - .env                  
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '8080:80'
    depends_on:
      - db

  frontend:
    build:
      context: ./ui-onlybuns
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ui-onlybuns:/src/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:               