version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d 
    ports:
      - '5432:5432'

  pgadmin:                     # ← add this
    image: dpage/pgadmin4
    env_file:
      - .env                  # loads PGADMIN_DEFAULT_*
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:               